//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDataWin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int id { get; set; }
        public int turmas_id { get; set; }
        public int alunos_id { get; set; }
        public Nullable<decimal> valor_nota { get; set; }
    
        public virtual alunos alunos { get; set; }
        public virtual turmas turmas { get; set; }
    }
}
